# Generated by Django 2.0 on 2018-10-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=15, null=True),
        ),
    ]
