# Generated by Django 2.0 on 2018-10-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_cliente_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBanco', models.CharField(max_length=25)),
                ('codigo', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
                ('SiNo', models.CharField(choices=[('s', 'Si'), ('n', 'No')], max_length=15, null=True)),
            ],
        ),
    ]
