# Generated by Django 2.0 on 2018-10-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCuenta', models.CharField(max_length=10, null=True)),
                ('usuario', models.CharField(max_length=10)),
                ('contrasenia', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
    ]
