# Generated by Django 2.0 on 2018-10-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_auto_20181023_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correoAlterno',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
