# Generated by Django 2.0 on 2018-10-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_auto_20181023_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
