# Generated by Django 2.0 on 2018-10-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_cuenta_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(max_length=50, null=True, unique_for_date='%d-%m-%Y'),
        ),
    ]
