# Generated by Django 2.0 on 2018-10-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0008_auto_20181023_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=25)),
                ('receptor', models.CharField(max_length=25)),
                ('cantidad', models.CharField(max_length=25)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
