# Generated by Django 2.0 on 2018-11-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0009_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
