# Generated by Django 2.0 on 2018-11-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0010_cliente_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('cedula', models.CharField(max_length=10)),
                ('genero', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=15, null=True)),
                ('fechaNacimiento', models.DateField(max_length=50, null=True, unique_for_date='')),
                ('correo', models.CharField(max_length=30, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
